### ISSUE TITLE
vico_vps: Got a crash trying to run it on a dedicated server (with default config)

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ErdbeerbaerLP/Discord-Chat-Integration#1]
https://paste.dimdev.org/cumifuvipe.rb

**Comment by lordvico** [comment]
It happens everytime i try to boot the server.

Using Debian 9 headless and OpenJDK for run the server.

**Comment by ErdbeerbaerLP** [comment]
Can you send me a whole log file? The crash just tells me that a method could not be found. I checked the jar and the method *does* exist

**Comment by lordvico** [comment]
https://gist.github.com/lordvico/cdb2ace6f0e2cbf7d05ef4af1a489e5a < debug.log, latest.log and crash-reports.txt

**Comment by ErdbeerbaerLP** [comment]
Can you try if this file fixed it? I manually updated a dependency of JDA.
http://erdbeerbaerapi.tk/dcintegration-1.0.2TEST.jar

**Comment by ErdbeerbaerLP** [comment]
oops

**Comment by ErdbeerbaerLP** [comment]
Just wait, till the file is approved on curseforge

**Comment by lordvico** [comment]
Sorry, i wasnt near my server this weekend, thats why i didnt tested it

**Comment by ErdbeerbaerLP** [comment]
If you want to download it now, use this url. Curseforge takes too long.
http://erdbeerbaerapi.tk/dcintegration-1.0.2.jar

**Comment by lordvico** [comment]
Got this error in the console:

```
[21:49:08] [main/ERROR] [FML]: Unable to read the jar file dcintegration-1.0.2.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_212]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_212]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_212]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_212]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_212]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:200) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:169) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:97) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2838-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2838-universal.jar:?]
```

**Comment by ErdbeerbaerLP** [comment]
Looks like the file got corrupted while uploading with a bad connection. Re uploaded it, so it should work now

**Comment by ErdbeerbaerLP** [comment]
Or use curseforge, the new version is now online

**Comment by lordvico** [comment]
Thanks, will test now!
