### ISSUE TITLE
Server Chat not appearing in discord

### ISSUE THREAD

**Issue by mantis2600** [ErdbeerbaerLP/Discord-Chat-Integration#108]
Not sure if this is still maintained. We've  gotten the discord chat to show up in the minecraft server, but when we chat there it does not appear in the discord channel. It throws the following error. Any help would be greatly appreciated. 

https://pastebin.com/jwKDDpVc

**Comment by StoneMasons4106** [comment]
I'm getting the same issue, posting error below:
←[m←[1;31m[14:22:04] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:405) ~[?:1.3.3] {re:classloading}
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:284) ~[?:1.3.3] {re:classloading}
        at de.erdbeerbaerlp.dcintegration.DiscordIntegration.chat(DiscordIntegration.java:363) ~[?:1.3.3] {re:classloading,re:mixin}
        at net.minecraftforge.eventbus.ASMEventHandler_29_DiscordIntegration_chat_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:450) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

**Comment by ErdbeerbaerLP** [comment]
Looks like FTBUtilities changed something.
Will update in a few days

**Comment by StoneMasons4106** [comment]
Thank you. Also, some players are able to send messages, and others can't. This is from one of the players who can't. I checked and they're set up correctly in the linked players file, and they have the correct mods installed. So not sure what's happening there. Appreciate the help!

**Comment by mantis2600** [comment]
I updated to the current version of FTBU (5.4.1.130) and FTBL (5.4.7.2) for 1.12 and this issue is resolved. Didn't realize I didn't have the most recent edition.
