### ISSUE TITLE
Server Chat not Appearing with DC Integration

### ISSUE THREAD

**Issue by StoneMasons4106** [ErdbeerbaerLP/Discord-Chat-Integration#111]
Posting here since #108 got closed.

←[m←[1;31m[14:22:04] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:405) ~[?:1.3.3] {re:classloading}
at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:284) ~[?:1.3.3] {re:classloading}
at de.erdbeerbaerlp.dcintegration.DiscordIntegration.chat(DiscordIntegration.java:363) ~[?:1.3.3] {re:classloading,re:mixin}
at net.minecraftforge.eventbus.ASMEventHandler_29_DiscordIntegration_chat_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:450) ~[?:?] {re:classloading}
at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading}
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

Of note, running 1.15.2, 31.2.36 Forge, and this modpack: https://www.curseforge.com/minecraft/modpacks/masonsmodpack

Please take a look when you have the chance.

**Comment by StoneMasons4106** [comment]
Another example just today:

←[m←[1;31m[21:57:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: de.erdbeerbaerlp.dcintegration.DiscordIntegration@34ae4c0d chat(Lnet/minecraftforge/event/ServerChatEvent;)V
java.lang.NullPointerException
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:405)
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:284)
        at de.erdbeerbaerlp.dcintegration.DiscordIntegration.chat(DiscordIntegration.java:363)
        at net.minecraftforge.eventbus.ASMEventHandler_32_DiscordIntegration_chat_ServerChatEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:450)
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:976)
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36)
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9)
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714)
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641)
        at java.lang.Thread.run(Unknown Source)

←[m←[1;31m[21:57:06] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:405) ~[?:1.3.3] {re:classloading}
        at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:284) ~[?:1.3.3] {re:classloading}
        at de.erdbeerbaerlp.dcintegration.DiscordIntegration.chat(DiscordIntegration.java:363) ~[?:1.3.3] {re:classloading,re:mixin}
        at net.minecraftforge.eventbus.ASMEventHandler_32_DiscordIntegration_chat_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:450) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dcintegration.json:MixinNetHandlerPlayServer,pl:mixin:A}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

**Comment by StoneMasons4106** [comment]
Any thoughts as to what this could be? Ripped out and reinstalled Forge and mods, no luck.

**Comment by ErdbeerbaerLP** [comment]
I will try to fix this as soon as I have time

**Comment by StoneMasons4106** [comment]
This started happening to a second player on the server. Just a heads up. Still no idea why.

**Comment by StoneMasons4106** [comment]
Still an issue.
