### ISSUE TITLE
Server Crash/Web Socket Shutdown Event

### ISSUE THREAD

**Issue by StoneMasons4106** [ErdbeerbaerLP/Discord-Chat-Integration#114]
Posting error log here. Only player on was mining:

←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] ERROR WebSocketClient - There was an error in the WebSocket connection
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]: java.lang.NoClassDefFoundError: net/dv8tion/jda/api/events/ShutdownEvent
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:424)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:log:272]:
        at dcshadow.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]: Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.events.ShutdownEvent
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:
        at java.lang.ClassLoader.findClass(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:
        at java.lang.ClassLoader.loadClass(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:104)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:
        at java.lang.ClassLoader.loadClass(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:279]:
        ... 8 more
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for net.dv8tion.jda.api.events.ShutdownEvent
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:242)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            ... 9 more
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    Caused by: java.nio.channels.ClosedChannelException
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at sun.nio.ch.FileChannelImpl.position(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at sun.nio.ch.FileChannelImpl.position(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:952)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:931)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1500)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1430)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:547)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at java.nio.file.Files.newInputStream(Unknown Source)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at net.minecraftforge.fml.loading.ModJarURLHandler$ModJarURLConnection.getInputStream(ModJarURLHandler.java:73)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:166)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:230)
←[m←[32m[13:32:28] [JDA MainWS-ReadThread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:            ... 11 more
←[m←[1;31m[13:33:26] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
←[m←[1;31m[13:33:26] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
←[m←[1;31m[13:33:27] [Server Watchdog/ERROR] [minecraft/ServerHangWatchdog]: This crash report has been saved to: C:\Users\Jake\Desktop\.\crash-reports\crash-2020-09-15_13.33.27-server.txt

Running 1.15.2-1.3.3 version, config file attached.
[dcintegration-common.txt.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5226791/dcintegration-common.txt.zip)

**Comment by StoneMasons4106** [comment]
Closing, Extended Nether the issue, not DC Integration
