### ISSUE TITLE
1.16.4 Server hang bug again when restarting / stopping[BUG] 

### ISSUE THREAD

**Issue by Ki-Tan2934** [ErdbeerbaerLP/Discord-Chat-Integration#148]
**What happened?**
-Server does not close down and hangs

**What should happen?**
-Server should stop

**Steps to reproduce**
- Linux Ubuntu 20.04
- /stop on server
- does not close down

**Version**
- 1.16.4

DiscordIntegration-2.0.1

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*
Default

**Crash report if available (use https://paste.dimdev.org)**
- none

**Additional info**

-Worked on 1.16.3 version before updating to 1.16.4

**Comment by sfPlayer1** [comment]
There are a couple non-daemon threads (again), which would at least have a chance to disturb post-crash exit, server thread is long gone in the following dump:

```
"JDA RateLimit-Worker 1" #89 prio=5
idle TIMED_WAITING waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@287c3353
        at java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@14.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
        at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)

"JDA RateLimit-Worker 2" #90 prio=5
"JDA RateLimit-Worker 3" #96 prio=5
"JDA RateLimit-Worker 4" #114 prio=5
"JDA RateLimit-Worker 5" #142 prio=5
idle WAITING waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@287c3353
        at java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
        at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:505)
        at java.base@14.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
        at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1614)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)

"Webhook-RateLimit Thread WebhookID: 123" #143 prio=5
idle WAITING waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@25b6f97b
        at java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
        at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:505)
        at java.base@14.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
        at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1614)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170)
        at java.base@14.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
        at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
```
