### ISSUE TITLE
Error during shutdown.

### ISSUE THREAD

**Issue by CyaNox** [ErdbeerbaerLP/Discord-Chat-Integration#15]
Error while shutting down the server using the `stop` command potentially causing unclean shutdowns:
```
[05:35:19] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@136a5986:
java.lang.NullPointerException: FTBLib Universe == null!
        at com.feed_the_beast.ftblib.lib.data.Universe.get(Universe.java:108) ~[Universe.class:?]
        at de.erdbeerbaerlp.dcintegration.DiscordIntegration.formatPlayerName(DiscordIntegration.java:134) ~[DiscordIntegration.class:?]
        at de.erdbeerbaerlp.dcintegration.DiscordIntegration.playerLeave(DiscordIntegration.java:326) ~[DiscordIntegration.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_650_DiscordIntegration_playerLeave_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580) [FMLCommonHandler.class:?]
        at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:388) [pl.class:?]
        at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:853) [pa.class:?]
        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:453) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:291) [pa$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
        at net.minecraft.server.MinecraftServer.callFromMainThread(MinecraftServer.java:1383) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.addScheduledTask(MinecraftServer.java:1395) [MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.disconnect(NetHandlerPlayServer.java:287) [pa.class:?]
        at net.minecraft.server.management.PlayerList.removeAllPlayers(PlayerList.java:1084) [pl.class:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:431) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579) [MinecraftServer$4.class:?]
```

This happens when someone (or multiple people) are still on the server while it is shutting down.

**Comment by ErdbeerbaerLP** [comment]
Try the new one, should be fixed now
https://www.curseforge.com/minecraft/mc-mods/dcintegration/files

**Comment by CyaNox** [comment]
Seems good so far. Haven't seen the error pop up since 1.1.4.
