### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by SodiumShine** [ErdbeerbaerLP/Discord-Chat-Integration#209]
Game client crashed to desktop

Forge 36.0.14
Minecraft 1.16.5
Mod version 2.1.0-1.16

```
[22:47:47] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration@218aca4c advancement(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
		2: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/AdvancementEvent;)V
java.lang.NullPointerException
	at de.erdbeerbaerlp.dcintegration.common.storage.PlayerLinkController.getSettings(PlayerLinkController.java:244)
	at de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.advancement(DiscordIntegration.java:150)
	at net.minecraftforge.eventbus.ASMEventHandler_117_DiscordIntegration_advancement_AdvancementEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1043)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:213)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35)
	at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72)
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234804_a_(SourceFile:54)
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234803_a_(SourceFile:50)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71111_a(ServerPlayerEntity.java:1529)
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:129)
	at net.minecraft.inventory.container.Container.func_75132_a(Container.java:99)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71116_b(ServerPlayerEntity.java:332)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:230)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[22:47:47] [Server thread/FATAL]: Preparing crash report with UUID 628903fc-38e2-459a-a917-1424b61866e5
[22:47:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at de.erdbeerbaerlp.dcintegration.common.storage.PlayerLinkController.getSettings(PlayerLinkController.java:244) ~[dcintegration:2.1.0]
	at de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.advancement(DiscordIntegration.java:150) ~[dcintegration:2.1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_117_DiscordIntegration_advancement_AdvancementEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1043) ~[forge:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:213) ~[?:?]
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?]
	at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72) ~[?:?]
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234804_a_(SourceFile:54) ~[?:?]
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234803_a_(SourceFile:50) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71111_a(ServerPlayerEntity.java:1529) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:129) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75132_a(Container.java:99) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71116_b(ServerPlayerEntity.java:332) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:230) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 6 more
```
Full log
[latest.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5943517/latest.log)

**Comment by ErdbeerbaerLP** [comment]
Remove it from the client. It is an Server-Side only mod
