### ISSUE TITLE
Rate limits during server startup/shutdown

### ISSUE THREAD

**Issue by Derkades** [ErdbeerbaerLP/Discord-Chat-Integration#235]
The mod works almost perfectly, except it extends server startup and shutdown by 5+ minutes while spewing rate limit messages to the console `WARN RateLimiter - Encountered 429 on route`

**Version**
-
- [x] 1.12
- [ ] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 

**Config file**
-
https://paste.derkad.es/pebuqahifi.toml

**Comment by Derkades** [comment]
I have a feeling it's related to updating channel descriptions during startup/shutdown, so I've tried compiling from master with that commented out but I get this (jar generated by `./gradlew build`, no forge experience)
```
Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.newInstance(Class.java:412)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
    ... 24 more
 ```

**Comment by Derkades** [comment]
Rate limit issues are gone with `B:MODIFY_CHANNEL_DESCRIPTRION=false`

**Comment by ErdbeerbaerLP** [comment]
This feature is no longer supported because discord increased the rate limit way to high for this feature
