### ISSUE TITLE
[BUG] Couldn't load

### ISSUE THREAD

**Issue by MAMAdzwoni** [ErdbeerbaerLP/Discord-Chat-Integration#40]
**What happened?**
-Crash on startup 

**What should happen?**
-Plugin should start

**Steps to reproduce**
- place plugin in /plugins
- start the server

**Version**
Paperspigot 1.15.2 `This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
Mod version `Feb 12, 2020`

**Crash report if available (use https://paste.dimdev.org)**
```
[16:39:03 ERROR]: Could not load 'plugins/dcintegration-1.1.14-1.15.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:147) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-105]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
```

**Additional info**
- Host OS: Raspbian (ARM)

**Comment by ErdbeerbaerLP** [comment]
Weird...
`Jar does not contain plugin.yml`
If you open the jar with winrar or semilar (maybe an linux tool), does the jar contain the plugin.yml? If not, you may need to re-download it

**Comment by ErdbeerbaerLP** [comment]
I was able to run the command on my raspberry
![image](https://user-images.githubusercontent.com/27149563/74867210-8ca1e580-5354-11ea-8637-cec51c1058d8.png)
(make sure you are downloading the spigot plugin from here: https://www.spigotmc.org/resources/discordrichpresence-customizer.59796/update?update=308746)

**Comment by MAMAdzwoni** [comment]
looks like it
