### ISSUE TITLE
[Bug]: Fabric 1.21.3 immediate crash on startup without creating config | (also your Discord server links are outdated)

### ISSUE THREAD

**Issue by EpyonProjects** [ErdbeerbaerLP/Discord-Chat-Integration#596]
### What happened?

Placing dcintegration-fabric-MC1.21.3-3.1.0.jar in my /mods/ folder.  Restart server, immediately crashes.  No config file is generated

### Game Version

Other

### What platform are you using?

Fabric

### Platform version

0.16.9

### Config File

```toml
N/A
```

### Crash report / Error log (if applicable)

```shell
[20:24:36] [main/ERROR]: Mixin apply for mod dcintegration-fabric failed dcintegration.mixins.json:ServerPlayerMixin from mod dcintegration-fabric -> net.minecraft.class_3222: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onPlayerDeath could not find any targets matching 'die' in net/minecraft/class_3222. Using refmap dcintegration-fabric-like-MC1.21.3-fabric-like-refmap.json [INJECT_PREPARE Applicator Phase -> dcintegration.mixins.json:ServerPlayerMixin from mod dcintegration-fabric -> Prepare Injections -> handler$zbh001$dcintegration-fabric$onPlayerDeath(Lnet/minecraft/class_1282;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onPlayerDeath could not find any targets matching 'die' in net/minecraft/class_3222. Using refmap dcintegration-fabric-like-MC1.21.3-fabric-like-refmap.json [INJECT_PREPARE Applicator Phase -> dcintegration.mixins.json:ServerPlayerMixin from mod dcintegration-fabric -> Prepare Injections -> handler$zbh001$dcintegration-fabric$onPlayerDeath(Lnet/minecraft/class_1282;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
        at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_1294.<clinit>(class_1294.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) [server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) [server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) [server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) [server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) [server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
[20:24:36] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_1294.<clinit>(class_1294.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_1294.<clinit>(class_1294.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dcintegration.mixins.json:ServerPlayerMixin from mod dcintegration-fabric] from phase [DEFAULT] in config [dcintegration.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_1294.<clinit>(class_1294.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onPlayerDeath could not find any targets matching 'die' in net/minecraft/class_3222. Using refmap dcintegration-fabric-like-MC1.21.3-fabric-like-refmap.json [INJECT_PREPARE Applicator Phase -> dcintegration.mixins.json:ServerPlayerMixin from mod dcintegration-fabric -> Prepare Injections -> handler$zbh001$dcintegration-fabric$onPlayerDeath(Lnet/minecraft/class_1282;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
        at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_1294.<clinit>(class_1294.java:47) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63438(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63053(class_2246.java:1287) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.method_63064(class_2246.java:1300) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2246.<clinit>(class_2246.java:315) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2966.method_12851(class_2966.java:53) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
        ... 4 more
```

**Comment by benshan36** [comment]
Can you post your crash report? It should’ve generated a crash report log in /crash-reports

**Comment by EpyonProjects** [comment]
I have a log, but no crash report.   Even restarting multiple times, for some reason I am not getting a new crash report
[2024-12-04-7.log](https://github.com/user-attachments/files/18015458/2024-12-04-7.log)

**Comment by benshan36** [comment]
I tried everything I could to replicate your issue and couldn't. It's likely a mod incompatibility issue. My first recommendations is to redownload dcintegration and see if try to reinstall it to verify it's not corrupted. if that doesn't fix it, I recommend playing around with removing mods to see if it's one of them that is causing it to crash

**Comment by sonicer105** [comment]
I Just tired to add it to my sever and got the same mixin injection error.

Here's the Latest.log: https://gist.github.com/sonicer105/260314c918f40c21e453ec33a19ee99d

Edit: Additionally, no report is generated in `/crash-reports`

**Comment by ErdbeerbaerLP** [comment]
hmm... looking at it, it's something I encountered in-dev. Semi-reproducable. Some builds had it, some builds worked fine.

Will need to investigate

**Comment by sonicer105** [comment]
Cool. Let me know if there's anything I can provide to help with this.

**Comment by Obbaron** [comment]
I have encountered the same issue as well. If no solution is found, I'll check if it is a mod incompatibility issue this weekend. I have quite a few mods currently

[latest.log](https://github.com/user-attachments/files/18038192/latest.log)

**Comment by FlyingPotato-131** [comment]
same exact issue, it's not a mod incompatibility (happens even without any mods aside from fabric api) and it persists even if there is a config file (copied from a 1.21 instance)

**Comment by sonicer105** [comment]
updating to the newly released `dcintegration-fabric-MC1.21.3-3.1.0.1.jar` version does appear to fix the crash for me. OP should give it another go.
