### ISSUE TITLE
Questionmark as command prefix throws an issue

### ISSUE THREAD

**Issue by 4rz0** [ErdbeerbaerLP/Discord-Chat-Integration#7]
I set up '?' as my command prefix, but on the usage of any command, an error is instead thrown by the server:
```
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0
?
^
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.error(Pattern.java:1957)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.sequence(Pattern.java:2125)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.expr(Pattern.java:1998)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.compile(Pattern.java:1698)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.<init>(Pattern.java:1351)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.util.regex.Pattern.compile(Pattern.java:1028)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at java.lang.String.replaceFirst(String.java:2178)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at de.erdbeerbaerlp.dcintegration.Discord.onEvent(Discord.java:326)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:128)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:868)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:766)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:745)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:903)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[20:30:55] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at dcshadow.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

Forge is 1.12.2-14.23.5.2836
Mod version is 1.0.9

**Comment by ErdbeerbaerLP** [comment]
It is because it can´t override aliases of the /help command. Might add a way to disable some default commands

**Comment by ErdbeerbaerLP** [comment]
Oops, misread something, reopenig it...
